### PR TITLE
Add cp910

### LINKED ISSUE #3: Support for code page 910
Having support for code page 910 would be useful for a project I'm working on.

### PR DESCRIPTION
**Pull request by EnderShadow**
Resolves #3

### CODE REVIEW

**Comment by EnderShadow** [comment]
I based this off of [Wikipedia](https://en.wikipedia.org/wiki/Digital_encoding_of_APL_symbols#Code_page_910), but I'm unsure if characters 0-31 and 127 are properly mapped since I haven't been able to find any other sources for this code page outside of Wikipedia and Turing Complete which appears to use the same encoding.

**Comment by bonega** [comment]
Thanks for your PR, I will try and get this one merged this weekend :+1:

**Comment by bonega** [comment]
Hey,
Can you activate "allow edits by maintainers"?
I had some trouble to push some added commits to your PR

**Comment by EnderShadow** [comment]
That's already checked. Not sure what the issue would be. Maybe we could merge it into a different branch so you could push the relevant changes and then merge into master?

**Comment by bonega** [comment]
Ok, I will check what the problem is later.
In the meantime, you can pull: https://github.com/bonega/yore/tree/cp910
into your branch and the pr should be updated

**Comment by EnderShadow** [comment]
I just pushed your changes into my branch

**Comment by bonega** [comment]
Thank you, I will push a new release tonight

**Pull request merged**
